config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  
  resources :tasks

  post "tasks/:id/toggle", to: "tasks#toggle"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
end #validation

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index #responsable to show the tasks
    #start filter
        filter_by_completed = params[:completed]

        if filter_by_completed.nil? || filter_by_completed == 'All'
          @tasks = Task.all
        elsif filter_by_completed == 'Pending'
            @tasks = Task.where(completed: false)
        else
            @tasks = Task.where(completed: true)
        end
    #end filter

        @task = Task.new #new task
    end

    def show #specific task
        @task = Task.find(params[:id])
    end

    def create #create task
        @task = Task.new(task_params)

        respond_to do |format|
            if @task.save
                format.html { redirect_to tasks_url, notice: "Task was created" }
            else
                format.html {render :new, status: :unprocessable_entity}
            end
        end
    end

    def toggle #update task complete
        @task = Task.find(params[:id])
        @task.update(completed: params[:completed])

       puts({ message: "Success" }.to_json)
    end

    def edit #specifict task
        @task = Task.find(params[:id])
    end

    def update #update the task
        @task = Task.find(params[:id])
        respond_to do |format|
            if @task.update(task_params)
            format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
            else
            format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy #delete
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_url, notice: "Post was successfully deleted."
    end

    private  #for security

    def task_params
        params.require(:task).permit(:title, :description, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="m-0">
    <main class="h-screen m-0">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="flex ">
<%= form_with(model: task, class: "mb-5") do |form| %> <!--generete a form associeted to the model task-->
    <div class="flex flex-col">
         <%= form.text_field :title, required: true, placeholder: "Add Task", class: "inline-block sm:flex-row text-violet-900 px-3 py-2 mt-2 shadow rounded-md border border-violet-200 outline-none" %>
    </div>
    <div class="flex flex-col sm:flex-row sm:space-x-2 sm:items-center">
          <%= form.text_field :description, placeholder: "Description", class: "inline-block  sm:flex-row text-violet-900 px-3 py-2 mt-2 shadow rounded-md border border-violet-200 outline-none" %>
          <%= form.date_field :due_date, required: true, class: "inline-block  sm:flex-row text-violet-900 px-2 py-2 mt-2 shadow rounded-md border border-violet-200 outline-none" %>
          <%= form.submit "Save", class: "btn sm:flex-row py-2 mt-2 bg-violet-600 text-white" %>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class=""> <!--block-->
    <turbo-frame id="<%= dom_id task %>" class="block">
        <%= form_with(model: task, class:"text-l inline-block my-3 p-3 m-2 w-auto") do |form|%> <!--render form that represent the task-->
        <div class="flex items-start justify-between min-h-10">
            <%= form.check_box :completed, 
                                data: {
                                    id: task.id,
                                    action: "tasks#toggle"
                                    },
                                class: "mr-2 align-middle bg-violet-50 border-violet-400 focus:ring-violet-500 h-5 w-5 rounded checked:bg-violet-600 hover:bg-violet-400"%>
        
            <div class="ml-2 inline-block ">   
                <div class="text-xl text-violet-900"><%= task.title %></div>
                <div class="text-violet-900"><%= task.description %> </div>
                <div class="text-violet-400"><%= task.due_date.strftime("%b %d") %> </div>
            
                <% end %>
            
                <div class="me-8 flex space-x-2">
                    <%= link_to "Edit", edit_task_path(task),
                            class: "btn bg-violet-200 text-violet-900" %>

                    <%= button_to "Delete", task_path(task), method: :delete, data: { "turbo-frame": "_top" }, class: "btn bg-violet-200 text-violet-900" %>
                </div>
            </div>
        </div>
    </turbo-frame>
</div>

app/views/tasks/edit.html.erb
<div  class="min-w-80 max-w-3xl p-5 m-2 bg-cover" style="background-image: url('https://i.pinimg.com/564x/ae/df/b2/aedfb2094f51330330e83f667e2272a1.jpg')">
  <h1 class="font-bold text-blue-900 text-2xl mb-3">Editing Task</h1>

  <turbo-frame id="<%= dom_id @task %>" class="block">
    <%= render "form", task: @task %>
    <%= link_to "Back", tasks_path, class: "btn mb-3 bg-violet-200 text-violet-900" %>
  </turbo-frame>
</div> 

app/views/tasks/index.html.erb
<div class="p-5 m-2 w-full min-h-screen bg-cover bg-center" style="background-image: url('https://i.pinimg.com/564x/02/c7/16/02c71634350c8926f80b8007cba9bb11.jpg')">
<!--   -->
    <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline" id="notice"> 
            <%= notice %>
        </p>
    <%end%> <!--message of the controller-->

    <div class=""> <!--my-5 flex-->
        <h1 class="font-bold text-2xl text-blue-900 md:text-3xl lg:text-4xl">To do list</h1>
    </div>

    <div class=""> <!--mt-8 flex-->
        <%= render "form", task: @task %> <!--render the form-->
    </div>

    <div id="tasks" class="justify-center">
        <h1 class="font-bold text-blue-900 text-lg mb-7">Tasks</h1>
        <!-- start filter -->
        <%= form_tag tasks_path, method: :get do %>
            <div class="inline-block text-violet-900"> <%= label_tag :completed %> </div>
            <%= select_tag :completed, options_for_select(["All", "Pending", "Done"], params[:completed] || "All"), class: "inline-block text-violet-900 w-32 px-3 py-2 mt-2 my-6 shadow rounded-md border border-gray-200 outline-none" %>
            <%= submit_tag "Search", class:"text-violet-900" %>
        <% end %> 
        <!-- end filter -->
    </div>
    <div class="px-5" data-controller="tasks">
        <%= render @tasks%>
    </div> <!--render the task-->
</div>